main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.farah, name='farah'),
    path('experience/', views.experience, name='experience'),  
    path('profile/', views.identitas, name='identitas'), 
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/',include('story5.urls'), name="story5"),
    path('story6/',include('story6.urls'), name="story6"),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.add, name='add'),
    path('ListSchedule/', views.ScheduleList ,name = 'ScheduleList'),
    path('detail/P<int:pk1>/',views.detail, name='detail'),
    path('delete/P<int:pk>/', views.delete, name='delete')
    
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('addkegiatan/',views.addkegiatan,name='addkegiatan'),
    path('listkegiatan/', views.listkegiatan, name='listkegiatan'),
    path('addpeserta/<int:org_id>/', views.addpeserta, name='addpeserta'),
]

main/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Schedule (models.Model) :
    course = models.CharField(max_length=50, blank=False)
    lecturer = models.CharField(max_length=50, blank=False)
    sks = models.IntegerField(blank=False)
    place = models.CharField(max_length=20, blank=False)
    year = models.CharField(max_length=20, blank=False)
    description = models.CharField(max_length=150, blank=False)

    

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100)
    def __str__(self):
        return self.nama_kegiatan


class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=50)
    kegiatan = models.ForeignKey(
                Kegiatan, 
                on_delete=models.CASCADE,
                blank=True,
                null=True)
    def __str__(self):
        return self.nama_peserta

story5/forms.py
from django import forms

class FormSched(forms.Form) :
    course = forms.CharField(
        max_length = 100,
        widget=forms.TextInput(
            attrs={
            'class' : 'form-control',
            'placeholder' : 'Course',
            'type' : 'text',
            'required' : True
    }))

    lecturer = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'class' : 'form-control',
            'placeholder' : 'Lecturer',
            'type' : 'text',
            'required' : True
    }))

    sks = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : "Number of Credits",
                'type' : 'number',
                'required' : True
    }))

    place = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Place',
                'type' : 'text',
                'required' : True
    }))


    year = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Ex: Gasal 2017/2018',
                'type' : 'text',
                'required' : True
    }))


    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Description',
                'type' : 'text',
                'required' : True
    }))

story6/forms.py
from django import forms


class FormKegiatan(forms.Form):
    nama_kegiatan = forms.CharField(
        label="Nama kegiatan",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-60',
                'placeholder' : 'Ketik disini',
                'type' : 'text',
            }
        )
    )


class FormPeserta(forms.Form):
    nama_peserta = forms.CharField(
        label="Nama Lengkap",
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder' : 'Ketik disini',
                'type' : 'text',
            }
        )
    )

main/views.py
from django.shortcuts import render


def farah(request):
    return render(request, 'main/farah.html')

def identitas(request):
    return render(request, 'main/identitas.html')

def experience(request):
    return render(request, 'main/experience.html')
    

story5/views.py
from django.shortcuts import render, redirect
from .forms import FormSched
from .models import Schedule

# Create your views here.
def add(request) :
    if request.method == 'POST':
        form = FormSched(request.POST)
        if (form.is_valid()) :
            ScheduleFix = Schedule()
            ScheduleFix.course = form.cleaned_data['course']
            ScheduleFix.lecturer = form.cleaned_data['lecturer']
            ScheduleFix.sks = form.cleaned_data['sks']
            ScheduleFix.place = form.cleaned_data['place']
            ScheduleFix.year = form.cleaned_data['year']
            ScheduleFix.description = form.cleaned_data['description']
            ScheduleFix.save()
        return redirect('/story5')
    else :
        form = FormSched()
        schedule = Schedule.objects.all()
        context = {
            'Form' : form,
            'schedule' : schedule
        }
        return render(request, 'addschedule.html', context)

def ScheduleList(request) :
    schedule = Schedule.objects.all()
    return render(request, 'listschedule.html', {'listschedule':schedule})


def delete(request, pk):
    try:
        sched_delete = Schedule.objects.get(pk = pk)
        sched_delete.delete()
        return redirect('/story5/ListSchedule')
    except:
        return redirect('/story5/ListSchedule')

def detail(request, pk1):
    try:
        sched_detail = Schedule.objects.get(pk = pk1)
        context = {
            'sched':sched_detail
        }
        return render(request, 'detailschedule.html',context)
    except:
        return redirect('/story5/ListSchedule')

story6/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import FormKegiatan, FormPeserta
from .models import Kegiatan, Peserta

def index(request):
    return render(request,'index.html')

def addkegiatan(request):
    form_kegiatan = FormKegiatan()
    if request.method == "POST":
        form_input1 = FormKegiatan(request.POST)
        if form_input1.is_valid():
            kegiatan = Kegiatan()
            kegiatan.nama_kegiatan = form_input1.cleaned_data['nama_kegiatan']
            kegiatan.save()
            return redirect('/story6/addkegiatan')
        else:
            return render(request, 'addkegiatan.html', {'form': form_kegiatan, 'status': 'failed'})
    else:
        return render(request, 'addkegiatan.html', {'form': form_kegiatan})

def listkegiatan(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    return render(request, 'listkegiatan.html', {'kegiatan': kegiatan, 'peserta': peserta})

def addpeserta(request, org_id):
    form_peserta = FormPeserta()
    if request.method == "POST":
        form_input2 = FormPeserta(request.POST)
        if form_input2.is_valid():
            peserta = Peserta()
            peserta.nama_peserta = form_input2.cleaned_data['nama_peserta']
            peserta.kegiatan = Kegiatan.objects.get(id=org_id)
            peserta.save()
            return redirect('/story6/listkegiatan')
        else:
            return render(request, 'addpeserta.html', {'form': form_peserta, 'status': 'failed'})
    else:
        return render(request, 'addpeserta.html', {'form': form_peserta})

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <header class="header fixed-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm py-3">
      <div class="container">
          <a class="navbar-brand" href="{% url 'main:farah' %}">
            <small class="font-weight-bold mb-0 text-uppercase">Farah Husna Nabilah</small>
          </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'main:farah' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'main:experience' %}">Experience</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'main:identitas' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'story5:add' %}">Add Schedule</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'story5:ScheduleList' %}">List Schedule</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'index' %}">Add Activity</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  {% block content %}
  
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/farah.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
    <title>Farah Husna Nabilah</title>
  {% endblock meta %}

  {% block content %}
  <header class="header fixed-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm py-3">
      <div class="container">
        <a class="navbar-brand" href="#">
          <small class="font-weight-bold mb-0 text-uppercase">Farah Husna Nabilah</small>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
              <a data-smooth class="nav-link scroll-link" href="#home">Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="#education">Education</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="#skills">Skills</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="#achievements">Achievements</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="#contact">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'main:experience' %}">Experience</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'main:identitas' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link scroll-link" href="{% url 'story5:add' %}">Add Schedule</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <section class=" section2 py-5 header text-center text-white mt-5" id="home">
    <div class="container py-5 text-white">
      <header class="py-5 my-lg-5">
        <h1 class="font7">Hallo Everyone!</h1>
        <p class="font-italic mb-1">Welcome to my personal website </p>
        <a class="btn btn-outline-light px-4 rounded-pill scroll-top" href="#about">Are you curious about me?</a>
      </header>
    </div>
  </section>
  
  <section class="py-5 d-flex" id="about">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-5 md-auto">
        <p><img src="{% static 'img/farhus.jpg' %}"class= "img1 img-responsive rounded-circle" align="left"> </p>
      </div>
        <div class="col-lg-6 md-auto">
       <p class="font6">
          About me
          <br>Farah Husna Nabilah
          <br>Information System Student
        </p><p class="font-italic mb-5 font12">I’m usally called Farah. I was born on Bekasi on July 28, 2001.
        I’m Indonesian. I’m class of 2019 and currently student majoring
        in Information Systems, Faculty of Computer Science, University
        of Indonesia. I like interacting with other people. I adapt easily to
        new environments. My hobbies are singing, reading and cooking.
        I’m a perfectionist. I’m a person who likes to work hard and never
        gives up. My motto is “take a risk or lose the chance”. I have good
        time management. I have interest in business and marketing.</p>
        <a class="btn btn-outline-dark px-4 rounded-pill scroll-top" href="https://drive.google.com/file/d/1TjiSZsQHFrv8waGijeqeUEx1t9IdQM53/view?usp=sharing">Download CV</a>
      </div>
    </div>
  </div>
  </section>
  <section class="py-5 d-flex" id="education">
    <div class="container py-5">
      <h2 align="center" class="font7">Educational Background</h2>
      <br>
      <br>
      <div class=" row-text-center">
      <p align="center" ><img src="{% static 'img/Makara_UI.png' %}" class="img4"> </p>
      <h1 align= "center" class="font3">University of Indonesia</h1>
      <p align= "center" class="font4">Bachelor of Computer Science </p>
      <p align= "center" class="font5">2019 - 2023 (Expected)</p>
<br>
<br><p align="center"><img src="{% static 'img/sman2bekasi.png' %}" class="img4"> </p>
      <h1 align="center" class="font3">SMAN 2 Bekasi</h1>
      <p align="center" class="font4">Science Major</p>
      <p align="center" class="font5">2016 - 2019</p>
<br>
<br>
     <p align = "center"> <a class="btn btn-outline-dark px-4 rounded-pill scroll-top" href="{% url 'main:experience' %}">See my full experience</a></p>
    </div> 
  </div>
  </section>
  
  <section class="py-5 d-flex align-items-center" id="skills">
    <div class="container py-5">
      <h2 align="center" class="font7">Skills</h2>
      <br>
      <br>
      <div class="row">
        <div class="col-lg-4 ">
          <div class="border2">
            <p align="center" class="font8">  PROFESSIONAL<br> SKILL</p>
            <p class="font9">Copywriting</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0"
                aria-valuemax="100"></div>
            </div>
            <p class="font9">HTML/CSS</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="25" aria-valuemin="0"
                aria-valuemax="100"></div>
            </div>
            <p class="font9">Java</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="25" aria-valuemin="0"
                aria-valuemax="100"></div>
            </div>
            <p class="font9">Python</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="25" aria-valuemin="0"
                aria-valuemax="100"></div>
            </div>
            <br>
          </div>
        </div>
        <div class="col-lg-4 ">
          <div class="border2">
          <p align="center" class="font8"> PERSONAL <br> SKILL</p>
          <p class="font9">Leadership</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Teamwork</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Communication</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Problem Solving</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Public Speaking</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <br>
          </div>
        </div>
        <div class="col-lg-4 ">
          <div class="border2">
          <p align="center"class="font8"> TOOLS <br> SKILL</p>
          <p class="font9">Microsoft Office</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Figma</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Adobe Photoshop</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <p class="font9">Canva</p>
          <div class="progress" style="height: 20px;">
            <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0"
              aria-valuemax="100"></div>
          </div>
          <br>
          </div>
        </div>
      </div>

  </section>
  
  <section class="py-5 d-flex align-items-center" id="achievements">
    <div class="container py-5">
      <h2 align="center" class="font7">Achievements</h2>
      <br>
      <br>
      <div class="row">
        <div class="col-lg-6 mx-auto">
         <p align="center"> <img src="{% static 'img/piala 1.JPG' %}" class="img3 rounded-circle"> </p>
        <div align="center">
          <p align="center" class="border1 font11">RUNNER UP 1
            <br>CHOIR COMPETITION</p>
        </div>
        </div>
        <div class="col-lg-6 mx-auto">
          <p align ="center"><img src="{% static 'img/piala 2.JPG' %}" class="img3 rounded-circle"> </p>
          <div align="center"> <p align ="center" class="border1 font11">RUNNER UP 1
          <br>CHOIR COMPETITION</p>
            </div>
        </div>
      </div>
    </div>
    
  </section>

  <!-- Demo section 4 -->
  <section class="py-5 d-flex align-items-center" id="contact">
  <div class="container py-5">
    <div class="row text-center">
      <div class="col-lg-9 mx-auto">
        <h2 class="font10">For Business Inquiries</h2>
      <table align="center">
        <br>
        <tbody>
          <tr>
            <th><img src="{% static 'img/logohp.png' %}" width="40px" height="40px"></th>
            <td align="left" class="font9"> 085814264038 </td>
          </tr>
          <tr>
            <th><img src="{% static 'img/logoemail.png' %}" width="40px" height="40px"></th>
            <td align="left" class="font9"> farah.husna@ui.ac.id </td>
          </tr>
          <tr>
            <th><img src="{% static 'img/logolinked.png' %}" width="45px" height="45px"></th>
            <td align="left" class="font9"> Farah Husna Nabilah </td>
          </tr>
              <tr>
                <th><img src="{% static 'img/logorumah.png' %}" width="45px" height="45px"></th>
                <td align="left" class="font9"> Pekayon Jaya, Bekasi Selatan, Kota Bekasi </td>
              </tr>
      
        </tbody>
      </table>
      </div>
    </div> <div class="container py-5">
      <div class="row text-center">
        <div class="col-lg-9 mx-auto">
          <h2 class="font10">Get me in Contact</h2>
          <br>
          <a href="https://www.facebook.com/farahhusna28/"><img src="{% static 'img/logofb.png' %}" height="50" width="50" /></a>
          &nbsp
          &nbsp
          &nbsp
          <a href="https://www.linkedin.com/in/farah-husna-nabilah-b87991199/"><img src="{% static 'img/logolinkedin.png' %}" height="50"
              width="50" /></a> 
              &nbsp
              &nbsp
              &nbsp
              <a href="https://www.instagram.com/husnafarah/"><img src="{% static 'img/iglogo.png' %}" height="50"
              width="50" /></a>
              &nbsp
              &nbsp
              &nbsp
              
                  <a href="https://wa.me/6285814264038"><img src="{% static 'img/logowa.png' %}" height="50"
                  width="50" /></a>   
            </div>
            </div>
              <br>
              <br>
              <br>
              <br>
              <p align="center"> <a align="center" class="btn btn-outline-dark rounded-pill scroll-top" href="#home">Back to
                  Top</a> </p>
            </section>

            {% endblock content %}

story5/templates/addschedule.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<title>Create Shedule</title>
<style>
  body {
    background-color: #89CCF7;
  }
  </style>
{% endblock meta %}

{% block content %}
<br>
<br>
<br>
<br>
<br>

<h1 align="center" class="font7"> Create Your Schedule</h1>
    <form action='' method="POST">
        {% csrf_token %}
        {{ Form }}
        <br>
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Add Schedule">
        </div>
    </form>

    <div>
      {% for sched in add %}
    </div>
    <p>{{sched.course}}</p>
    <p>{{sched.lecturer}}</p>
    <p>{{sched.sks}}</p>
    <p>{{sched.place}}</p>
    <p>{{sched.year}}</p>
    <p>{{sched.description}}</p>
    </div>
    {% endfor %}
  </div>

  
  {% endblock content %}

story5/templates/detailschedule.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<title>Detail Schedule</title>
<style>
     body {
    background-color:#89CCF7;
  }
  .one {
    color: rgb(0, 0, 0);
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    font-size: 20px;
    line-height: 2
  }
</style>
{% endblock meta %}

{% block content %}


<div>
    <br>
    <br>
    <br>
    <h1 align="center" class="font7"> This is your detail schedule!</h1>
    <br>
    <br>
    <table align="center" border="0" class = " one table-responsive-md">
        <tbody>
            <tr>
                <th align="left">Course</th>
                <td>:</td>
                <td>{{sched.course}}</td>
            </tr>
            <tr>
                <th align="left">Lecturer</th>
                <td>:</td>
                <td>{{sched.lecturer}}</td>
            </tr>
            <tr>
                <th align="left">Number of Credits</th>
                <td>:</td>
                <td>{{sched.sks}}</td>
            </tr>
            <tr>
                <th align="left">Place</th>
                <td>:</td>
                <td>{{sched.place}}</td>
            </tr>
            <tr>
                <th align="left">Year</th>
                <td>:</td>
                <td>{{sched.year}}</td>
            </tr>
            <tr>
                <th align="left">Description</th>
                <td>:</td>
                <td>{{sched.description}}</td>
            </tr>

            
            </tbody>
    </table>
    
    
    </div>

    </div>
    <br>
    <br>
    <div align = "center">
<a href="{% url 'story5:ScheduleList' %}">
    <button align="center" class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>Back to List Schedule</button>
</a> </div>

    
    
    {% endblock content %}

story5/templates/listschedule.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<title>List Shedule</title>
<style>
     body {
    background-color:#89CCF7;
  }
  .one {
    color: rgb(0, 0, 0);
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    font-size: 20px;
    line-height: 2
  }
</style>
{% endblock meta %}

{% block content %}


{% if listshedule.count == 0 %}
<br>
<br>
<br>
<h1 align="center" class="font7"> List Schedule</h1>
<br>
<br>
<br>
    <h1>You don't have any schedule</h1>
    <a href="{% url 'story5:add' %}">
        <button align="center" class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>Add New Schedule</button>
    </a>

{% else %}

<div>
    <br>
    <br>
    <br>
    <h1 align="center" class="font7"> List Schedule</h1>
    <br>
    <br>
    {% for sched in listschedule %}
    <table align="center" border="0" class = " one table-responsive-md">
        <tbody>
            <tr>
                <th align="left">Course</th>
                <td>:</td>
                <td>{{sched.course}}</td>
            </tr>
            <tr>
                <th align="left">Lecturer</th>
                <td>:</td>
                <td>{{sched.lecturer}}</td>
            </tr>
            <tr>
                <th align="left">Place</th>
                <td>:</td>
                <td>{{sched.place}}</td>
            </tr>
            </tbody>
    </table>
    <br>
    <p align="center">
        <a href="{% url 'story5:detail' pk1=sched.pk %}">
            <button align="center" class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>Detail Schedule</button>
        </a>
    </p>
    <p align="center">
        <a href="{% url 'story5:delete' pk=sched.pk %}">
            <button align="center" class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>Delete Schedule</button>
        </a>
    </p>
            <br>
            <br>
            {% endfor %}
    </div>

    </div>


    {% endif %}
    
    
    
    {% endblock content %}